ANNOTATION:
  CATEGORY: Coffee
DATA_LOADER:
  CROP_SIZE: 224
  NUM_WORKERS: 0
  PIN_MEMORY: true
  SAMPLING_FPS: 2
  SHUFFLE: false
EGO_ERROR:
  ANNS_PATH: /data/egoproceldata/Coffee/annotations/normal
  FRAMES_PATH: /data/egoproceldata/Coffee/frames
  VIDEOS_PATH: /data/egoproceldata/Coffee/videos/normal
LAV:
  CONTRIB_PERCENT: 0.0
  USE_CIDM: false
LOG:
  DIR: /data/egoproceldata/Coffee/logs
  LEVEL: debug
MISC:
  DEBUG_VIZ_PATH: ''
  VERBOSE: true
TCC:
  BATCH_SIZE: 2
  BILSTM: false
  CONTEXT_STRIDE: 15
  DATA_PATH: /data/egoproceldata/Coffee/videos/normal
  KMEANS_NUM_CLUSTERS: 30
  LSTM: false
  MODEL_PATH: /data/egoproceldata/Coffee/logs/checkpoint_07131_loss-24.3889.pt
  NUM_CONTEXT_STEPS: 2
  NUM_FRAMES: 32
  TRAIN_EPOCHS: 10000
