ANNOTATION:
  CATEGORY: SpicedHotChocolate
DATA_LOADER:
  CROP_SIZE: 224
  NUM_WORKERS: 0
  PIN_MEMORY: true
  SAMPLING_FPS: 2
  SHUFFLE: false
EGO_ERROR:
  ANNS_PATH: /data/error_dataset/annotations
  FRAMES_PATH: /data/error_dataset/frames
  VIDEOS_PATH: /data/error_dataset/categories
LAV:
  CONTRIB_PERCENT: 0.1
  USE_CIDM: true
LOG:
  DIR: /data/error_dataset/logs/SpicedHotChocolate
  LEVEL: debug
MISC:
  DEBUG_VIZ_PATH: ''
  VERBOSE: true
TCC:
  BATCH_SIZE: 2
  BILSTM: false
  CONTEXT_STRIDE: 15
  DATA_PATH: /data/error_dataset/categories/SpicedHotChocolate
  KMEANS_NUM_CLUSTERS: 30
  LSTM: false
  MODEL_PATH: /data/logs/SpicedHotChocolate/checkpoint_09409_loss-6.9992.pt
  NUM_CONTEXT_STEPS: 2
  NUM_FRAMES: 32
  TRAIN_EPOCHS: 10000
