EGO_ERROR:
  VIDEOS_PATH: /data/error_dataset/categories
  ANNS_PATH: /data/error_dataset/annotations
  FRAMES_PATH: /data/error_dataset/frames
ANNOTATION:
  CATEGORY: RecipeName
DATA_LOADER:
  NUM_WORKERS: 0
  SHUFFLE: False
  CROP_SIZE: 224
  SAMPLING_FPS: 2
  PIN_MEMORY: True
MISC:
  DEBUG_VIZ_PATH: ""
  VERBOSE: True
LOG:
  DIR: /data/error_dataset/logs/RecipeName
  LEVEL: debug
TCC:
  DATA_PATH: /data/error_dataset/categories/RecipeName
  TRAIN_EPOCHS: 10000
  KMEANS_NUM_CLUSTERS: 30
  BATCH_SIZE: 2
  NUM_FRAMES: 32
  NUM_CONTEXT_STEPS: 2
  CONTEXT_STRIDE: 15
  LSTM: False
  BILSTM: False
  MODEL_PATH: /data/logs/RecipeName/checkpoint_04230_loss-5.3154.pt
LAV:
  USE_CIDM: True
  CONTRIB_PERCENT: 0.1
